port: 8080
apiKey: apiKey

databaseConfig:
  url: "jdbc:postgresql://localhost:5432/"
  driver: "org.postgresql.Driver"
  user: "postgres"
  password: "postgres"
  databaseName: "ktor_sample"

catFactConfig:
  baseUrl: "https://catfact.ninja"
